### ISSUE TITLE
Невозможно запустить приложение больше чем под одним пользователем

### ISSUE THREAD

**Issue by wtlz** [otymko/phoenixbsl#107]
Запустил экземпляр, другие пользователи на этом же терминале уже не могут. Копирование папки не помогает.
![image](https://user-images.githubusercontent.com/32014902/88522369-ea6ee380-cffe-11ea-8183-0786a5507964.png)
Можете поправить?

**Comment by otymko** [comment]
@wtlz проблему понял, добавлю проверку по пользователю ОС.

**Comment by otymko** [comment]
@wtlz попробуйте сборку: https://github.com/otymko/phoenixbsl/actions/runs/191754019

**Comment by wtlz** [comment]
> @wtlz попробуйте сборку: https://github.com/otymko/phoenixbsl/actions/runs/191754019

на терминале не возможности установить - можете JAR файл присоединить, пожалуста?

**Comment by wtlz** [comment]
проверяем - уже не ругается на запущенную копию, но не стартует проверка BSL по CTRL+i

**Comment by wtlz** [comment]
![28C46AD4](https://user-images.githubusercontent.com/32014902/91528462-703cc200-e910-11ea-979e-9162a623f008.PNG)
нет, не запускается даже приложение - перед тестом предварительно завершили все сеансы.

**Comment by otymko** [comment]
@wtlz странно. Проверю

**Comment by otymko** [comment]
@wtlz Пробуйте https://www.dropbox.com/s/p9exzr05pca64yi/phoenix-0.3.7%2B38.dev.jar?dl=0

**Comment by otymko** [comment]
@wtlz теперь работает
