### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by shalimski** [otymko/phoenixbsl#11]
[main] ERROR org.github.otymko.phoenixbsl.Launcher - Приложение упало. Причина [Ljava.lang.StackTraceElement;@481a15ff

Возникает java.lang.NullPointerException
com.sun.jna.platform.win32.COM.COMInvoker._invokeNativeObject(COMInvoker.java:42)

**Comment by otymko** [comment]
@shalimski буду копаться. Нужно знать какая операционная система.

**Comment by shalimski** [comment]
Windows 7 Professional x64 Version 6.1.7601

**Comment by otymko** [comment]
@shalimski проблема из используемой либы:
https://github.com/mmarquee/ui-automation/issues/52

подумаю как решить для поддержки win 7

**Comment by otymko** [comment]
Видимо поможет переход на jna + winapi

**Comment by otymko** [comment]
Перевод на winapi через jna откладывается до начала Ноября. Ну ли если найдется желающий реализовать=)

**Comment by otymko** [comment]
@shalimski попробуй версию msi -> https://github.com/otymko/phoenixbsl/releases/download/0.2.1/phoenixbsl-0.2.1.msi

**Comment by shalimski** [comment]
Да, заработало
