### ISSUE TITLE
Неправильно рассчитывается номер версии при сборке в master

### ISSUE THREAD

**Issue by otymko** [otymko/phoenixbsl#117]
![image](https://user-images.githubusercontent.com/11651847/101306758-54827980-3878-11eb-8eee-b29c68da6ddc.png)

**Comment by nixel2007** [comment]
Потому что при сборке у тебя репо грязный. Смотри, какие файлы создаются и помещай их в игнор

**Comment by otymko** [comment]
@nixel2007 ага, так оно и есть. Конечно сборка просит себя переписать уже давно
