### ISSUE TITLE
При проверке выделенной части кода требуется проверять весь модуль и выполнять отбора ошибок по номеру строки

### ISSUE THREAD

**Issue by BProg-Gladkov** [otymko/phoenixbsl#123]
Я Выделяю несколько строк кода, которые менял и запускаю проверку.
Ожидаю, что будет проверен весь модуль (что бы получить полный контекст), а ошибки будут отобраны по выделенному коду.
Фактически выполняется проверка только выделенных строк.
Такая проверка часто не имеет смысла.

Пример:
![image](https://user-images.githubusercontent.com/33430119/107914558-bb589900-6f73-11eb-89aa-8e74d5ccce39.png)

**Comment by otymko** [comment]
@BProg-Gladkov попробуйте сборку https://github.com/otymko/phoenixbsl/actions/runs/939946010

**Comment by nonameformr** [comment]
проверил на 0.5.0, работает ;)

**Comment by otymko** [comment]
Реализовано

**Comment by nixel2007** [comment]
@otymko я так и не понял, почему ты не используешь отбор в x-diagnostics, который я специально для этого добавлял :)
