### ISSUE TITLE
При проверке модуля (Ctrl + I ) устанавливается признак модифицированности коонфигурации

### ISSUE THREAD

**Issue by marv-ua** [otymko/phoenixbsl#147]
![image](https://user-images.githubusercontent.com/81148850/149784341-ce08c2fc-b977-436c-a067-cc721467ebf7.png)

**Comment by otymko** [comment]
@marv-ua феникс-бсл для взаимодействия с конфигуратором использует буфер обмена и "кнопонажималку". Других законных способов взаимодействия с конфигуратором я пока не нашел.

**Comment by nonameformr** [comment]
Так если происходит просто проверка кода, без изменения...

**Comment by krv2k** [comment]
Подниму вопрос. Откуда признак модифицированности, если мы для проверки просто копируем в буфер, но ничего обратно не вставляем?

**Comment by nixel2007** [comment]
> Подниму вопрос. Откуда признак модифицированности, если мы для проверки просто копируем в буфер, но ничего обратно не вставляем?

В текущую позицию в тексте вставляется символ-маркер, а после проверки вырезается. Выделение текста сбивает текущий фокус, а маркер позволяет сфокусироваться обратно.

**Comment by krv2k** [comment]
> > Подниму вопрос. Откуда признак модифицированности, если мы для проверки просто копируем в буфер, но ничего обратно не вставляем?
> 
> В текущую позицию в тексте вставляется символ-маркер, а после проверки вырезается. Выделение текста сбивает текущий фокус, а маркер позволяет сфокусироваться обратно.

Спасибо, теперь понятно зачем это сделано.

**Comment by nixel2007** [comment]
@otymko а при нажатии ctrl-g текущего номера строки в открытом окне нет?
