### ISSUE TITLE
ОШИБКА установки! Нет файлов для установки!

### ISSUE THREAD

**Issue by yarsergo** [otymko/phoenixbsl#148]
**Установка ms**i - нет ни одного файла  msi
Качаем из релизов файл msi.  ???? нет такого файла!
Устанавливаем на компьютере.
Первый раз запускаем под администратором (иначе не работает обработка нажатий кнопок, пока проблема решается).

**Запуск через jar** - нет ни одного файла jar !!! 
На компьютере должна быть установлена Java не ниже 11 версии. Если нет - устанавливаем.
Создаем новый каталог, из релизов копируем файл jar.

**phoenix-**   - нет ни одного такого файла!

есть только файлы **java** в "глубоко-закопанной" папке 
\src\main\java\com\github\otymko\phoenixbsl\logic
PhoenixAPI.java
PhoenixCore.java  
и т.д.

ReadMe - неправильный
опубликуйте MSI файл  и напишите ТОЧНЫЙ путь (название папки)
Качаем из релизов ... не понятно!
нет такой папки relises - нигде в проекте!

**Comment by nixel2007** [comment]
Releases - это не папка в репозитории. Это отдельный раздел в интерфейсе репозитория справа и/или сверху в зависимости от настроек интерфейса

**Comment by otymko** [comment]
@yarsergo речь о странице релизов (https://github.com/otymko/phoenixbsl/releases). Проверил, файлы на месте:

![image](https://user-images.githubusercontent.com/11651847/151646772-13eb66ed-437a-4748-bfbe-478318380f97.png)

**Comment by yarsergo** [comment]
ну я (как программист 1С) - читаю Readme - и "найти в релизах" не понял где это...  
да, спасибо за ответы.
надо бы сделать гипер-ссылку тогда на слово "релизы" чтобы сразу переходить куда надо.
Я привык, что все материалы просто в репозитории... и искал именно там, 
уж извините

**Comment by yarsergo** [comment]
т.е. в файле README.md - можно уточнить слово релизы... (хотя бы для раздела  Установки msi ) 
и лучше открытие релизов в отдельный пункт выделить... потому что надо ещё выбрать последний релиз.

### Установка msi

1. Открывает страницу [релизов](https://github.com/otymko/phoenixbsl/releases) и открываем последний (Latest) Релиз.
2. Качаем файл с расширением MSI: phoenixbsl-{НомерРелиза}.msi
3. Устанавливаем на компьютере (желательно под администратором).
4. Первый раз запускаем под администратором (иначе не работает обработка нажатий кнопок, пока проблема решается).
[README.md](https://github.com/otymko/phoenixbsl/files/7985451/README.md)
