### ISSUE TITLE
Добавление лишних символов ";" при нажатии Ctrl+J

### ISSUE THREAD

**Issue by yarik111** [otymko/phoenixbsl#150]
При вызове быстрого исправления Конструкции вида 
`"<ИмяПеременной> = ЖДАТЬ ...."  
`Заменяются на 
`"<ИмяПеременной> ; = ЖДАТЬ ...."` . 

Используемая версия BSLLS 0.19.1, Версия Phoenix 0.4.1 + dev

**Comment by nixel2007** [comment]
Попробуйте на бсл лс 0.20.0-rc.2

**Comment by yarik111** [comment]
В 0.20.0-rc.2 работает корректно. Спасибо.
