### ISSUE TITLE
Проблема с повторной установкой после удаления предыдущей версии.

### ISSUE THREAD

**Issue by MaxOmsky** [otymko/phoenixbsl#153]
![image](https://user-images.githubusercontent.com/79788208/191897260-b0570a52-a99a-480f-bc24-a15579b003bd.png)

Добрый день. 

Столкнулся с невозможностью установить версию 0.5.0 после ручного удаления 0.4.1. Возможно, остались какие то данные от предыдущей версии.

**Comment by nixel2007** [comment]
А что значит "ручное удаление"?

**Comment by MaxOmsky** [comment]
shift + delete по папке

**Comment by nixel2007** [comment]
Тогда точно остались. Установка из msi записывает данные о себе в реестр Windows. произведите удаление из установки и удаления программ

**Comment by MaxOmsky** [comment]
Пробовал. К сожалению, удаление через установку и удаление выдает ту же ошибку :( Остается попробовать почистить реестр вручную?

**Comment by nixel2007** [comment]
@otymko есть идеи про какого пользователя вообще речь? Я не смотрел манифест msi, но кажется, что созданию пользователя взяться просто неоткуда, только запись в аппдату

**Comment by MaxOmsky** [comment]
@nixel2007 Похоже, что проблема была в профиле пользователя. После удаления папки phoenixbsl оттуда все стало как нужно. Спасибо за помощь.

**Comment by otymko** [comment]
@nixel2007 что-то из коробки jpackage-а.
