### ISSUE TITLE
Некорректная обработка конструктора Запрос = Новый Запрос(ТекстЗапроса);

### ISSUE THREAD

**Issue by kasper076** [otymko/phoenixbsl#159]
Некорректно обрабатывает конструктор запроса вида:
```
Запрос = Новый Запрос(
     #Область ТекстЗапроса
         "ВЫБРАТЬ
             1 КАК ИмяПоля");
     #КонецОбласти
```

**Comment by kasper076** [comment]
При проверке кода модуля содержащего такой код выдается сообщение "Ошибка разбора исходного кода"

**Comment by nixel2007** [comment]
1. Проверьте с актуальной версией бсл лс.
2. Если на актуальной версии воспроизводится, то можно попробовать завести задачу в репозитории 1c-syntax/bsl-parser, но если честно, фиксить такое очень не хочется. Это сильно усложняет грамматику языка и замедляет анализ. Проще падать и просить не разрывать выражения инструкциями препроцессору. Едт такое тоже не обработает, кстати.

**Comment by kasper076** [comment]
Понял. Спасибо.
