### ISSUE TITLE
При форматировании Ctrl-K убирает строки #Вставка

### ISSUE THREAD

**Issue by ShootNICK-tm** [otymko/phoenixbsl#160]
phoenix 0.5.0 rc-1
bsl ls 0.23.1

До
``` bsl
&ИзменениеИКонтроль("ДобавитьКомандыПечати")
Процедура АЛЬТПФ_ДобавитьКомандыПечати(КомандыПечати)

	#Вставка
    ДобавитьКомандыПечатиВзвешивания(КомандыПечати);
	#КонецВставки

КонецПроцедуры
```

**Ctrl-K**

После:

```bsl
&ИзменениеИКонтроль ("ДобавитьКомандыПечати")
Процедура АЛЬТПФ_ДобавитьКомандыПечати(КомандыПечати)
	
	
	ДобавитьКомандыПечатиВзвешивания(КомандыПечати);
	
	
КонецПроцедуры
```

**Comment by nixel2007** [comment]
Можете воспроизвести такое поведение в vscode? Или это специфичная для феникса проблема?

**Comment by ShootNICK-tm** [comment]
> Можете воспроизвести такое поведение в vscode? Или это специфичная для феникса проблема?

Воспроизводится. Видимо феникс тут не при чем ).

Есть похожий : [3325](https://github.com/1c-syntax/bsl-language-server/issues/3325)

**Comment by nixel2007** [comment]
Отлично, спасибо. Да, значит, это надо в бсл лс чинить.
