### ISSUE TITLE
Ctrl+I убирает конец строки.

### ISSUE THREAD

**Issue by ZlobinDV** [otymko/phoenixbsl#29]
При использовании комбинации клавиш Ctrl+I в строке кода

ТекстЗапроса = ?(ЕстьПриходнаяСпецификация(СсылкаНаОбъект), ПолучитьТекстЗапросаПоСпецификациям_Новый(), ПолучитьТекстЗапросаДляОПЗС_Новый());

Последний символ ";" может быть изменен на "$" или полностью удален. 

Тестировал на последнем релизе 0.2.1.

**Comment by shalimski** [comment]
У меня иногда удаляет последний символ, иногда пол модуля, иногда весь модуль целиком. Взаимосвязь не нашел

**Comment by otymko** [comment]
Попробую посмотреть, в чем может быть причина.

**Comment by sfaqer** [comment]
Проблема в том что посылается cntrl+z т.е отменяется последнее действие в модуле, будь то печать последнего символа, или вставка половины модуля.
