### ISSUE TITLE
Не корректный переход к строке при проверке выделенного фрагмента

### ISSUE THREAD

**Issue by sfaqer** [otymko/phoenixbsl#31]
При проверке выделенного фрагмента, номер строки вычисляется в рамках выделенного фрагмента, а не в рамках модуля, и переход к строке адресует не на ту строку.
![image](https://user-images.githubusercontent.com/32082417/66725775-4ef9f100-ee78-11e9-900b-5f0f974b2ff5.png)

**Comment by otymko** [comment]
Надо проверить, т.к. вроде этой функциональностью я сейчас пользуюсь
