### ISSUE TITLE
Win10 Если феникс запущен не из под админа, то логи не создаются.

### ISSUE THREAD

**Issue by sfaqer** [otymko/phoenixbsl#73]
Т.к дефолтный путь хранения логов C:\Program Files\phoenixbsl\app\logs то для записи в него требуются повышенные привелегии, в случае если феникс запущен не из под админа, то логи просто не создаются.

Ожидаемое поведение:
1. Создавать логи в каталоге текущего пользователя, в appdata например.
2. В настройках рядом с папкой логов показывать уведомление в случае если нет прав на запись в каталог логов.

**Comment by otymko** [comment]
В этой версии логи пишутся в пользовательский каталог: https://github.com/otymko/phoenixbsl/actions/runs/31883237
